name: CI Pipeline Staging
on:
  pull_request:
    branches:
      - staging
    paths-ignore:
      - "README.md"
      - ".github/workflows/**"
  push:
    branches:
      - staging

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      DEV_SERVER_HOST: ${{ secrets.DEV_SERVER_HOST }}
      DEV_SERVER_USER: ${{ secrets.DEV_SERVER_USER }}
      DEV_SERVER_SSH_KEY: ${{ secrets.DEV_SERVER_SSH_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.4

      - name: Enable Corepack
        run: corepack enable

      - name: Activate pnpm
        run: corepack prepare pnpm@9.15.4 --activate
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Create environment file from GitHub secrets
        run: |
          echo "${{ secrets.ENV_AUTH_STAGING }}" > .env

      - name: Lint code
        run: pnpm run lint

      - name: Check code formatting
        run: pnpm run check-format

      - name: Check TypeScript types
        run: pnpm run check-types

      - name: Build project
        run: pnpm run build

      - name: Archive Build Artifacts
        run: |
          tar -czf open-school-portal-fe.tar.gz .next public package.json next.config.ts tsconfig.json pnpm-lock.yaml .env

      - name: Copy Artifacts to Server
        if: ${{ github.event_name == 'push' && env.DEV_SERVER_HOST != '' && env.DEV_SERVER_USER != '' && env.DEV_SERVER_SSH_KEY != '' }}
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ env.DEV_SERVER_HOST }}
          username: ${{ env.DEV_SERVER_USER }}
          key: ${{ env.DEV_SERVER_SSH_KEY }}
          source: open-school-portal-fe.tar.gz
          target: /tmp/staging/open-school-portal-fe-artifact.tar.gz
