name: CI Pipeline Production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - .github/workflows/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.4

      - name: Enable Corepack
        run: corepack enable

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Create environment file from GitHub secrets
        shell: bash
        run: echo "${{ secrets.ENV_AUTH_PROD }}" > .env

      - name: Lint code
        run: pnpm run lint

      - name: Check code formatting
        run: pnpm run check-format

      - name: Check TypeScript types
        run: pnpm run check-types

      - name: Build project
        run: pnpm run build

      - name: Archive Build Artifacts
        shell: bash
        run: tar -czf open-school-portal-fe.tar.gz .next public package.json next.config.ts tsconfig.json pnpm-lock.yaml .env

      - name: Copy Artifacts to Server
        if: ${{ github.event_name == 'push' }}
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
          sshpass -p "${{ secrets.PASSWORD }}" scp -o StrictHostKeyChecking=no open-school-portal-fe.tar.gz ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/tmp/prod/open-school-portal-fe-artifact.tar.gz
          rm -f open-school-portal-fe.tar.gz
